### ISSUE TITLE
21_ts_inspector not rendering sat image in split map mode

### ISSUE THREAD

**Issue by Niko-La** [giswqs/leafmap#145]
Ran the notebook # ts inspector on binder.

Entered a planet API but the split map is not showing satellite imagery. 

![image](https://user-images.githubusercontent.com/14004559/146626413-5174b38c-6631-4e32-8453-593005c71040.png)

**Comment by giswqs** [comment]
It works fine on my end. What geemap version are you using? Try `leafmap.update_package()` and restart the kernel. 

It might also be your API Key problem. Replace the `your-api-key` in the link below with your real api key and open the link in a browser. Make sure you can see a list of XYZ tile URLs on the page. Otherwise, your api key might not work. 

https://api.planet.com/basemaps/v1/services?api_key=your-api-key

![image](https://user-images.githubusercontent.com/5016453/146626690-c680228d-e112-4793-b409-19cefb036fbc.png)

**Comment by Niko-La** [comment]
tried the update with kernel restart.
I think my API key is the issue.
![image](https://user-images.githubusercontent.com/14004559/146627182-d2e1d6a2-ffb0-4a67-b6e8-d3b4c4544514.png)

**Comment by giswqs** [comment]
That means your API key does not have access to these tile layers. Did you apply for the account through the NICFI program? If yes, you should use `leafmap.planet_tiles_tropical()` (for tropical area only) rather than `leafmap.planet_tiles()` (for global mosaic).

![image](https://user-images.githubusercontent.com/5016453/146627218-911d208b-bcca-4e79-98c0-a4ad5f2d1844.png)

**Comment by Niko-La** [comment]
nope just used regular sign up.  it was working fine few months ago. not sure what happened will follow up with planet it.

**Comment by giswqs** [comment]
Make sure you have not accidentally leaked the api key somewhere online. I made that mistake before and my api key was disabled by Planet. It took a while to regain access.
