### ISSUE TITLE
In leafmap package, make all "add" methods consistent in the arguments they accept

### ISSUE THREAD

**Issue by philvarner** [giswqs/leafmap#262]
### Description

- Some methods (e.g., `add_cog_layer`) accept only a URL (`The URL of the COG tile layer.`)
- Some methods (e.g., `add_kml`) accept only a local file path (`The input file path to the KML.`)
- Some methods (e.g., `add_geojson`) accept a local file path, a URL, or a object (`The file path or http URL to the input GeoJSON or a dictionary containing the geojson.`)

It would be more ergonomic for users if all of these accepted either local path or URL.

I would recommend changing any method that accepts the object directly to have another method with a different clearer name instead of overloading the parameters, e.g., `add_geojson_from_dict`.

Related, some methods accept a parameter `layer_name` and some accept `name`, and it would be easier to use if all of them used a consistent name for all of the common parameters.

### Source code

n/a

**Comment by giswqs** [comment]
Good suggestions. I can make all add data functions accept both a local file path and HTTP URL. Regarding the `add_geojson_from_dict` function, the parameters will still be the same as `add_geojson`, I don't think it needs to be separate function in order to accept a dict input. 

I agree that it makes sense to use consistent parameter names, maybe changing all `layer_name` to just `name`. 

Pull request is welcome if you would like to contribute.

**Comment by philvarner** [comment]
This is great, thanks so much. I think this will make it much easier for new (and existing) users to work with. Thanks!
